# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow with schedule
  schedule:
    # Runs at 00:00 UTC every day
    - cron:  '0 0 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "update-problems-all"
  update-problems-all:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Setup Python
      - name: Setup Python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: '3.11'

      # Install dependencies
      - run: pip install -r requirements.txt
      
      # Runs fetch_problems_all.py
      - name: Run fetch_problems_all.py
        run: python fetch_problems_all.py
        env:
          LC_CF_CLEARANCE: ${{ secrets.LC_CF_CLEARANCE }}
          LC_CSRFTOKEN: ${{ secrets.LC_CSRFTOKEN }}
      
      # Commit problems_all.json
      - name: Commit problems_all.json
        uses: stefanzweifel/git-auto-commit-action@v4.12.0
        with:
          # Use different commit author name, differ from bunnyxt by default, avoid abuse of contribution graph
          commit_author: bunnyxt-ci <bunnyxt-ci@users.noreply.github.com>
          # Commit message
          commit_message: 'ci: update problems_all.json'
          # File pattern used for `git add`. For example `src/\*.js`
          file_pattern: problems_all.json
